[package]
name = "spatialos-sdk-sys"
version = "13.3.1"
authors = [
    "David Avedissian <git@dga.me.uk>",
    "Jamie Brynes <jamiebrynes7@gmail.com>"
]
edition = "2018"
links = "worker"
build = "build.rs"

[dependencies]

[build-dependencies]
lazy_static = "1.1.0"
