[package]
name = "spatialos-sdk-tools"
version = "0.0.0"
authors = ["Jamie Brynes <jamiebrynes7@gmail.com>"]
edition = "2018"

[[bin]]
name = "generate_bindings"
path = "src/generate_bindings/main.rs"

[dependencies]
clap = "2.32.0"
glob = "0.3"
bindgen = "0.55.1"
