[package]
name = "cargo-spatial"
version = "0.1.0"
authors = ["David LeGare <dlegare.1001@gmail.com>"]
edition = "2018"

[dependencies]
cargo_metadata = "0.7.1"
glob = "0.2.11"
log = "0.4.1"
rand = "0.6.5"
simplelog = "0.5.3"
serde = { version = "1.0.38", features = ["derive"] }
serde_json = "1.0.38"
spatialos-sdk-code-generator = { path = "../spatialos-sdk-code-generator" }
structopt = "0.2.14"
tap = "0.3.1"
toml = "0.4.10"
