[package]
name = "spatialos-sdk"
version = "0.0.0"
authors = [
    "Jamie Brynes <jamiebrynes7@gmail.com>",
    "David Avedissian <git@dga.me.uk>"
]
edition = "2018"

[dependencies]
derivative = "1.0.2"
spatialos-sdk-sys = { path = "../spatialos-sdk-sys"}
futures = "0.1.25"
inventory = "0.1"
lazy_static = "1.3"

[dev-dependencies]
compiletest_rs = { version = "0.3.19", features = ["stable"] }
structopt = "0.2.14"
tap = "0.3.0"
