[package]
name = "spatialos-sdk"
version = "0.0.0"
authors = [
    "Jamie Brynes <jamiebrynes7@gmail.com>",
    "David Avedissian <git@dga.me.uk>"
]
edition = "2018"

[dependencies]
spatialos-sdk-sys = { path = "../spatialos-sdk-sys"}
futures = "0.1.25"

[dev-dependencies]
uuid = { version = "0.7", features = ["v4"] }
structopt = "0.2.14"
tap = "0.3.0"
